name: team3-main-notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - matplotlib
  - scikit-learn
  - scikit-image
  - jupyter
  - pip
  - pip:
    - zenodo_get
    - netcdf4