name: 3286b92f-4fae-4cc6-a29e-e408bc844542
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - matplotlib
  - scikit-learn
  - scikit-image
  - jupyter
  - intake
  - pip
  - pip:
    - zenodo_get
    - netcdf4
    - intake_xarray
    - s3fs
    - h5netcdf